### ISSUE TITLE
Profiling memory usage of Go application

### ISSUE THREAD

**Issue by Jonathas-Conceicao** [koute/memory-profiler#39]
I was thinking about using this project to compare the memory usage of a Go application that I have rewritten in Rust, but when testing the memory-profiler with a simple go example it generated no result.

Heres the go example I've tested:
```go
package main

import "fmt"
import "os"
import "strconv"

func fib(n uint64) uint64 {
	switch n {
	case 0:
		return 0
	case 1:
		return 1
	default:
		return fib(n-1) + fib(n-2)
	}
}

func main() {
	input, _ := strconv.Atoi(os.Args[1])
	n := uint64(input)
	fmt.Println(fib(n))
}
```

And running:
```shell
go build test.go
LD_PRELOAD=/home/jonathas/Repositories/memory-profiler/target/release/libmemory_profiler.so ./test 40
```
Didn't generate any `dat` file at all. I have even tried adding a `make` or `new` calls to the fib `func` in order to introduce more allocations but I still got no results.

**Comment by koute** [comment]
Go uses a GC, so it's fundamentally incompatible with this profiler. In theory in may be possible to make it compatible by e.g. by adding fake `malloc`/`free`/etc. entry points to the profiler (that would only trigger the profiler without allocating any memory) and modifying Go's GC to trigger them, but that isn't a thing right now.

**Comment by otavio** [comment]
Your explanation makes sense, but closing this doesn't. As for us, other people might face the same issue, and keeping this open helps them to avoid losing time chasing it.

**Comment by arl** [comment]
Go has a builtin profiler (memory + cpu) no extra packages needed, https://go.dev/doc/diagnostics
@Jonathas-Conceicao
