### ISSUE TITLE
jemalloc

### ISSUE THREAD

**Issue by sklose** [koute/memory-profiler#42]
is there a way to use this tool with jemalloc? I set it up according to https://crates.io/crates/jemallocator. My profile file only includes a few allocations at the very beginning of the applications though. It looks like everything that was allocated with jemalloc is not captured. I am mainly interested in the memory fragmentation graph, which is why I can't just switch to the system allocator for profiling.

**Comment by tizoc** [comment]
Hello @sklose, were you able to figure this out? I'm right now at the exact same spot you were back then.

**Comment by koute** [comment]
The newest version on `master` now supports the `jemallocator` by default. (Only on AMD64)
