### ISSUE TITLE
PRELOAD exe error

### ISSUE THREAD

**Issue by wangshankun** [koute/memory-profiler#45]
$LD_PRELOAD=./libmemory_profiler.so ./test
thread '<unnamed>' panicked at 'attempted to leave type `lru::LruEntry<u64, nwind::frame_descriptions::CachedUnwindInfo>` uninitialized, which is invalid', /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/mem/mod.rs:658:9
![image](https://user-images.githubusercontent.com/3970271/103353552-20e7e780-4ae4-11eb-861f-d729c328e943.png)

**Comment by koute** [comment]
Fixed a long time ago.
